// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI3SJkOCdY5Z5lC5hiSiXPeKUwsYu-u2w',
    appId: '1:211551139323:web:f583360c18907986adc75e',
    messagingSenderId: '211551139323',
    projectId: 'fjfapp',
    authDomain: 'fjfapp.firebaseapp.com',
    storageBucket: 'fjfapp.firebasestorage.app',
    measurementId: 'G-GNBBWGHX3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-DWvTPnrmER5pee2IiQ-D4DEHhFay0gQ',
    appId: '1:211551139323:android:dc42f122d69b1c86adc75e',
    messagingSenderId: '211551139323',
    projectId: 'fjfapp',
    storageBucket: 'fjfapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8IdeicPj0cA3EtMcLM0ssfhs3xrLMudI',
    appId: '1:211551139323:ios:65cefa8708bd7211adc75e',
    messagingSenderId: '211551139323',
    projectId: 'fjfapp',
    storageBucket: 'fjfapp.firebasestorage.app',
    iosBundleId: 'com.example.fjfApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8IdeicPj0cA3EtMcLM0ssfhs3xrLMudI',
    appId: '1:211551139323:ios:65cefa8708bd7211adc75e',
    messagingSenderId: '211551139323',
    projectId: 'fjfapp',
    storageBucket: 'fjfapp.firebasestorage.app',
    iosBundleId: 'com.example.fjfApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI3SJkOCdY5Z5lC5hiSiXPeKUwsYu-u2w',
    appId: '1:211551139323:web:e03c369f6e1856a8adc75e',
    messagingSenderId: '211551139323',
    projectId: 'fjfapp',
    authDomain: 'fjfapp.firebaseapp.com',
    storageBucket: 'fjfapp.firebasestorage.app',
    measurementId: 'G-KXDJBLRPXV',
  );
}
