// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_test.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: TestFirebaseOptions.currentPlatform,
/// );
/// ```
class TestFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'TestFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'TestFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgveHztQMlNg9ahcAjJBhzhr4MUfXdIYY',
    appId: '1:39829597186:web:76f32b7731916204990b1b',
    messagingSenderId: '39829597186',
    projectId: 'fjfapp-test',
    authDomain: 'fjfapp-test.firebaseapp.com',
    databaseURL: 'https://fjfapp-test-default-rtdb.firebaseio.com',
    storageBucket: 'fjfapp-test.firebasestorage.app',
    measurementId: 'G-0RBH0ZJ4SW',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtibvFfLtu3OlbaGZFZlHxzWrJx_FIvDg',
    appId: '1:39829597186:ios:e5568d0e7b85d4bd990b1b',
    messagingSenderId: '39829597186',
    projectId: 'fjfapp-test',
    databaseURL: 'https://fjfapp-test-default-rtdb.firebaseio.com',
    storageBucket: 'fjfapp-test.firebasestorage.app',
    iosClientId: '39829597186-690dgslnockk20c8rrfbqsvvj82pq2rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.fjfApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtibvFfLtu3OlbaGZFZlHxzWrJx_FIvDg',
    appId: '1:39829597186:ios:e5568d0e7b85d4bd990b1b',
    messagingSenderId: '39829597186',
    projectId: 'fjfapp-test',
    databaseURL: 'https://fjfapp-test-default-rtdb.firebaseio.com',
    storageBucket: 'fjfapp-test.firebasestorage.app',
    iosClientId: '39829597186-690dgslnockk20c8rrfbqsvvj82pq2rs.apps.googleusercontent.com',
    iosBundleId: 'com.example.fjfApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyNWeDo7vtNd9wAYvtfrvZt7OL86D1mxM',
    appId: '1:39829597186:android:c71362eda04547c1990b1b',
    messagingSenderId: '39829597186',
    projectId: 'fjfapp-test',
    databaseURL: 'https://fjfapp-test-default-rtdb.firebaseio.com',
    storageBucket: 'fjfapp-test.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMMpPUDFQi2c0VJQkWMMBdk5tm1wPNtbU',
    appId: '1:39829597186:web:fcc2bddebeb950bd990b1b',
    messagingSenderId: '39829597186',
    projectId: 'fjfapp-test',
    authDomain: 'fjfapp-test.firebaseapp.com',
    databaseURL: 'https://fjfapp-test-default-rtdb.firebaseio.com',
    storageBucket: 'fjfapp-test.firebasestorage.app',
    measurementId: 'G-0PQ04F8QFH',
  );
}
