// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAe8_uy2W7Wyo88jAZGixaPLvjkV2nesY',
    appId: '1:893803829585:web:414ef54392ab4d6ef9db70',
    messagingSenderId: '893803829585',
    projectId: 'acefjf',
    authDomain: 'acefjf.firebaseapp.com',
    databaseURL: 'https://acefjf-default-rtdb.firebaseio.com',
    storageBucket: 'acefjf-us-storage',
    measurementId: 'G-GHY5150MH5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALO2-bRhdu7tTMm-Ixo2kXvLZ4JXCy-8c',
    appId: '1:893803829585:ios:26c74ac532b809d2f9db70',
    messagingSenderId: '893803829585',
    projectId: 'acefjf',
    databaseURL: 'https://acefjf-default-rtdb.firebaseio.com',
    storageBucket: 'acefjf-us-storage',
    iosClientId: '893803829585-gug1mrkak51qgcsg19s732k38g91iv5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fjfApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALO2-bRhdu7tTMm-Ixo2kXvLZ4JXCy-8c',
    appId: '1:893803829585:ios:26c74ac532b809d2f9db70',
    messagingSenderId: '893803829585',
    projectId: 'acefjf',
    databaseURL: 'https://acefjf-default-rtdb.firebaseio.com',
    storageBucket: 'acefjf-us-storage',
    iosClientId: '893803829585-gug1mrkak51qgcsg19s732k38g91iv5j.apps.googleusercontent.com',
    iosBundleId: 'com.example.fjfApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe_mP6DGidEAewkcObDinERnAEe2-nipY',
    appId: '1:893803829585:android:4f9e3135170694b1f9db70',
    messagingSenderId: '893803829585',
    projectId: 'acefjf',
    databaseURL: 'https://acefjf-default-rtdb.firebaseio.com',
    storageBucket: 'acefjf-us-storage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAe8_uy2W7Wyo88jAZGixaPLvjkV2nesY',
    appId: '1:893803829585:web:4dbfd5f8a377e49af9db70',
    messagingSenderId: '893803829585',
    projectId: 'acefjf',
    authDomain: 'acefjf.firebaseapp.com',
    databaseURL: 'https://acefjf-default-rtdb.firebaseio.com',
    storageBucket: 'acefjf-us-storage',
    measurementId: 'G-6YV4NEVGWC',
  );
}
