class BolaoConstants {
  static const List<String> phaseOptions = [
    "Todas as Fases", "Grupo A", "Grupo B", "Grupo C", "Grupo D", "Grupo E", "Grupo F",
    "Grupo G", "Grupo H", "Grupo I", "Grupo J", "Grupo K", "Grupo L", "16 Avos de Final",
    "Oitavas de Final", "Quartas de Final", "Semifinal", "Disputa 3º Lugar", "Final"
  ];

  static const Map<String, String> teamsFlagsMap = {
    'A Definir': '❓',
    'África do Sul': '🇿🇦',
    'Alemanha': '🇩🇪',
    'Arábia Saudita': '🇸🇦',
    'Argélia': '🇩🇿',
    'Argentina': '🇦🇷',
    'Austrália': '🇦🇺',
    'Áustria': '🇦🇹',
    'Bélgica': '🇧🇪',
    'Bósnia e Herzegovina': '🇧🇦',
    'Brasil': '🇧🇷',
    'Cabo Verde': '🇨🇻',
    'Canadá': '🇨🇦',
    'Catar': '🇶🇦',
    'Colômbia': '🇨🇴',
    'Coreia do Sul': '🇰🇷',
    'Costa do Marfim': '🇨🇮',
    'Croácia': '🇭🇷',
    'Curaçao': '🇨🇼',
    'Egito': '🇪🇬',
    'Equador': '🇪🇨',
    'Escócia': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'Espanha': '🇪🇸',
    'Estados Unidos': '🇺🇸',
    'França': '🇫🇷',
    'Gana': '🇬🇭',
    'Haiti': '🇭🇹',
    'Holanda': '🇳🇱',
    'Inglaterra': '🇬🇧',
    'Irã': '🇮🇷',
    'Iraque': '🇮🇶',
    'Japão': '🇯🇵',
    'Jordânia': '🇯🇴',
    'Marrocos': '🇲🇦',
    'México': '🇲🇽',
    'Noruega': '🇳🇴',
    'Nova Zelândia': '🇳🇿',
    'Panamá': '🇵🇦',
    'Paraguai': '🇵🇾',
    'Portugal': '🇵🇹',
    'RD Congo': '🇨🇩',
    'Senegal': '🇸🇳',
    'Suécia': '🇸🇪',
    'Suíça': '🇨🇭',
    'Tchéquia': '🇨🇿',
    'Tunísia': '🇹🇳',
    'Turquia': '🇹🇷',
    'Uruguai': '🇺🇾',
    'Uzbequistão': '🇺🇿',
  };
}
